// <auto-generated />
using System;
using FreshBake.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshBake.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908120758_AddCustomerProductCategory")]
    partial class AddCustomerProductCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessLevel", b =>
                {
                    b.Property<int>("AccessLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessLevelId"));

                    b.Property<string>("AccessLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessLevelId");

                    b.ToTable("AccessLevel");
                });

            modelBuilder.Entity("FreshBake.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomOrderNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FreshBake.API.Models.CustomerProduct", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerProducts");
                });

            modelBuilder.Entity("FreshBake.API.Models.CustomerProductCategory", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ProductCategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("CustomerProductCategories");
                });

            modelBuilder.Entity("FreshBake.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Chocolate Cake",
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Vanilla Sponge Cake",
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Red Velvet Cake",
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Carrot Cake",
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Apple Pie",
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Milk Tart",
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Lemon Meringue Pie",
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "White Bread Loaf",
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Whole Wheat Loaf",
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "Baguette",
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Bread Rolls",
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Croissants",
                            ProductCategoryId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Danish Pastries",
                            ProductCategoryId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "Vetkoek",
                            ProductCategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "Assorted Cupcakes",
                            ProductCategoryId = 5
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Cupcake Tower (Event)",
                            ProductCategoryId = 5
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Chocolate Chip Cookies",
                            ProductCategoryId = 6
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Shortbread",
                            ProductCategoryId = 6
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "Rusks",
                            ProductCategoryId = 6
                        });
                });

            modelBuilder.Entity("FreshBake.API.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1,
                            Name = "Cakes"
                        },
                        new
                        {
                            ProductCategoryId = 2,
                            Name = "Pies"
                        },
                        new
                        {
                            ProductCategoryId = 3,
                            Name = "Breads"
                        },
                        new
                        {
                            ProductCategoryId = 4,
                            Name = "Pastries"
                        },
                        new
                        {
                            ProductCategoryId = 5,
                            Name = "Cupcakes"
                        },
                        new
                        {
                            ProductCategoryId = 6,
                            Name = "Cookies & Biscuits"
                        });
                });

            modelBuilder.Entity("FreshBake.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FreshBake.API.Models.Customer", b =>
                {
                    b.HasOne("FreshBake.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("FreshBake.API.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshBake.API.Models.CustomerProduct", b =>
                {
                    b.HasOne("FreshBake.API.Models.Customer", "Customer")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshBake.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshBake.API.Models.CustomerProductCategory", b =>
                {
                    b.HasOne("FreshBake.API.Models.Customer", "Customer")
                        .WithMany("CustomerProductCategories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshBake.API.Models.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("FreshBake.API.Models.Product", b =>
                {
                    b.HasOne("FreshBake.API.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("FreshBake.API.Models.User", b =>
                {
                    b.HasOne("AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("FreshBake.API.Models.Customer", b =>
                {
                    b.Navigation("CustomerProductCategories");

                    b.Navigation("CustomerProducts");
                });

            modelBuilder.Entity("FreshBake.API.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
